name: Multi-Node Workflow

on: 
  workflow_dispatch:
  push:
    branches:
        - "main"

jobs:
  first-job:
     runs-on: ubuntu-latest
     steps:
        - name: Install the dependencies
          uses: actions/setup-node@v4
          with:
             node-version: 20

        - name: Verify the Installation of Nodejs and Npm 
          run: |
            node -v
            npm -v

        - name: Create a directory and initialize the node backend
          run: |
            mkdir -p backend
            cd backend 
            npm init -y
            npm install express

        - name: Upload backend as artifact
          uses: actions/upload-artifact@v4
          with: 
            name: backend-app
            path: backend

  second-job:
     runs-on: ubuntu-latest
     needs: first-job

     steps:
       - name: Download backend artifact
         uses: actions/download-artifact@v4
         with:
            name: backend-app

       - name: Add code to the server.js file
         run: |
           cat <<EOF> server.js
           const express = require("express");

           const app = express();
           const PORT = process.env.PORT ?? 6000;

           app.get("/", (req, res) => {
             res.json({
                message: "Server is running"
             });
           })

           app.listen(PORT, () => {
              console.log(`Server is up and running on port ${PORT}`);
           })
            
           EOF
 
       - name: Install dependencies
         run: |
            cd backend
            npm install
     
       - name: Run the App
         run: |
           cd backend
           node server.js
          
       - name: Echo if failure
         if: failure()
         run: |
          echo "Job Failed!!!"